obj-$(CONFIG_MAX14526)			+= muic.o
obj-$(CONFIG_MAX14526)			+= muic_maxim.o
obj-$(CONFIG_MAX14526)			+= muic_ti.o
obj-$(CONFIG_MAX14526)			+= fota.o
subdir-ccflags-$(CONFIG_MACH_STAR)      += -Iarch/arm/mach-tegra/